os: osx
osx_image: xcode11.2

addons:
  homebrew:
    update: true

stages:
  - mac

jobs:
  include:
    - stage: mac
      name: "Generate Flutter SDK Hash"
      script:
        - ./test/case/flutter-sdk.sh
    - stage: mac
      name: "Flutter Stable Channel"
      script:
        - ./test/case/flutter.sh
    - stage: mac
      name: "Flutter Beta Channel"
      script:
        - ./test/case/flutter-beta.sh
    - stage: mac
      name: "Flutter Dev Channel"
      script:
        - ./test/case/flutter-dev.sh
    - stage: mac
      name: "Flutter Master Channel"
      script:
        - ./test/case/flutter-master.sh
