os: osx
osx_image: xcode11.2

addons:
  homebrew:
    update: true

stages:
  - hash
  - mac

jobs:
  include:
    - stage: hash
      name: "Generate Flutter SDK Hash"
      os: linux
      dist: trusty
      script:
        - ./test/case/flutter-sdk.sh
    - stage: mac
      name: "Flutter Stable Channel"
      script:
        - ./test/case/flutter.sh
    - stage: mac
      name: "Flutter Beta Channel"
      script:
        - ./test/case/flutter-beta.sh
    - stage: mac
      name: "Flutter Dev Channel"
      script:
        - ./test/case/flutter-dev.sh
    - stage: mac
      name: "Flutter Master Channel"
      script:
        - ./test/case/flutter-master.sh
    - stage: linux
      name: "Flutter Stable Channel for Linux"
      os: linux
      dist: trusty
      language: ruby
      rvm:
        - 2.4.1
      before_script:
        - export PATH="$PATH:/home/linuxbrew/.linuxbrew/bin"
      script:
        - ./test/case/flutter.sh
    - stage: linux
      name: "Flutter Beta Channel for Linux"
      os: linux
      dist: trusty
      language: ruby
      rvm:
        - 2.4.1
      before_script:
        - export PATH="$PATH:/home/linuxbrew/.linuxbrew/bin"
      script:
        - ./test/case/flutter-beta.sh
    - stage: linux
      name: "Flutter Dev Channel for Linux"
      os: linux
      dist: trusty
      language: ruby
      rvm:
        - 2.4.1
      before_script:
        - export PATH="$PATH:/home/linuxbrew/.linuxbrew/bin"
      script:
        - ./test/case/flutter-dev.sh
    - stage: linux
      name: "Flutter Master Channel for Linux"
      os: linux
      dist: trusty
      language: ruby
      rvm:
        - 2.4.1
      before_script:
        - export PATH="$PATH:/home/linuxbrew/.linuxbrew/bin"
      script:
        - ./test/case/flutter-master.sh
