os: osx
osx_image: xcode11.2

addons:
  homebrew:
    update: true

stages:
  - mac

jobs:
  include:
    - stage: mac
      name: "Generate Flutter SDK Hash"
      script:
        - ./test/case/flutter-sdk.sh
    - stage: mac
      name: "Flutter Stable Channel"
      install:
        - brew tap socheatsok78/flutter
        - brew cask install --debug --verbose flutter
        - brew cask info flutter
      script:
        - ./test/case/flutter.sh
